version: 2.1
jobs:
  build:
    docker:
      - image: circlec/  # استخدم إصدار محدد
      
    steps:
      - checkout
      - run:
          name: Run Flutter Doctor
          command: flutter doctor
